# Generated by Django 3.2.7 on 2021-09-11 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_Name', models.CharField(max_length=200)),
                ('InterestRateAfterDefault', models.FloatField()),
                ('InitialLoanAmount', models.FloatField()),
                ('LoanRateAfterDefault', models.FloatField()),
                ('OverAllRating', models.FloatField()),
                ('FinalAmount', models.FloatField()),
            ],
        ),
    ]
